### ISSUE TITLE
Update homepage and navbar

### ISSUE THREAD

**Issue by ngchrbn** [TMS-GP/frontend#10]
**Tasks**
- [x] Update homepage:
   - [x] Update the styling (font size, hover effects, width, ...)
   - [x] Add hover effects
   - [x] Update most viewed courses component to use CourseCard
 
- [x] Update navbar:
   - [x] Update the styling (font size, hover effects, width, ...)
   - [x] Add hover effects
   - [x] Update the categories part to use actual categories from the backend
